#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mail
Version  : 1.4.5
Release  : 1
URL      : https://repo1.maven.org/maven2/javax/mail/mail/1.4.5/mail-1.4.5.jar
Source0  : https://repo1.maven.org/maven2/javax/mail/mail/1.4.5/mail-1.4.5.jar
Source1  : https://repo1.maven.org/maven2/javax/mail/mail/1.4.5/mail-1.4.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0
Requires: mvn-mail-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mail package.
Group: Data

%description data
data components for the mvn-mail package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/mail/mail/1.4.5
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/mail/mail/1.4.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/mail/mail/1.4.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/mail/mail/1.4.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.jar
/usr/share/java/.m2/repository/javax/mail/mail/1.4.5/mail-1.4.5.pom
