#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mail
Version  : 1.6.3
Release  : 2
URL      : https://github.com/eclipse-ee4j/mail/archive/1.6.3.tar.gz
Source0  : https://github.com/eclipse-ee4j/mail/archive/1.6.3.tar.gz
Source1  : https://repo1.maven.org/maven2/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.jar
Source2  : https://repo1.maven.org/maven2/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-2.0 GPL-2.0
Requires: mvn-mail-data = %{version}-%{release}
Requires: mvn-mail-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
See the [JavaMail web site](https://javaee.github.io/javamail).

%package data
Summary: data components for the mvn-mail package.
Group: Data

%description data
data components for the mvn-mail package.


%package license
Summary: license components for the mvn-mail package.
Group: Default

%description license
license components for the mvn-mail package.


%prep
%setup -q -n mail-1.6.3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-mail
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-mail/LICENSE.md
cp mail/src/main/resources/META-INF/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-mail/mail_src_main_resources_META-INF_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.jar
/usr/share/java/.m2/repository/com/sun/mail/mailapi/1.6.3/mailapi-1.6.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-mail/LICENSE.md
/usr/share/package-licenses/mvn-mail/mail_src_main_resources_META-INF_LICENSE.txt
